
version: '3.9'
services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
        - ./apps/api/.env #shared env file with strapi application 
    restart: unless-stopped
    

  #turborepo
  turbo:
    container_name: turbo
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    env_file:
        - ./.env #shared env file with strapi application 
    depends_on:
      - db
    command: sh -c "yarn install && yarn dev"
    volumes:
      - ./:/app/
       # Just specify a path and let the Engine create a volume
      - /app/node_modules/
    restart: on-failure

networks:
  turbo-network:
    driver: bridge